services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    networks:
      - app-network
    volumes:
      - frontend-build:/app/build
    command: >
      sh -c "npm run build && touch /app/build/BUILD_COMPLETE"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    networks:
      - app-network
    volumes:
      - frontend-build:/app/../frontend/build:ro
    depends_on:
      - frontend
    command: >
      sh -c 'while [ ! -f /app/../frontend/build/BUILD_COMPLETE ]; do
      echo "Waiting for frontend build..."; sleep 5; done &&
      gunicorn --bind 0.0.0.0:5000 run:app'

volumes:
  frontend-build: {}

networks:
  app-network:
    driver: bridge
